name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./src/challenge-envars/Dockerfile --tag davidpestana/challenge-env ./src/challenge-envars/

  build2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./src/challenge-envars/Dockerfile --tag davidpestana/challenge-env ./src/challenge-envars/
